In [1]:
import torch

In [16]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([1.3008, 0.6326, 0.2516], requires_grad=True)


In [17]:
y = x+2
print(y)

tensor([3.3008, 2.6326, 2.2516], grad_fn=<AddBackward0>)


In [20]:
z = y*y*2
# z = z.mean()
print(z)

tensor([21.7905, 13.8610, 10.1392], grad_fn=<MulBackward0>)


In [22]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([ 5.7214, 14.0404,  3.0111])


In [27]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad()

x = torch.randn(3, requires_grad=True)
print(x)
print(x + 2)

x.requires_grad_(False)
print(x)

y = x.detach()
print(y)

with torch.no_grad():
  z = x + 2
  print(z)

tensor([ 0.8907, -1.1050, -1.5195], requires_grad=True)
tensor([2.8907, 0.8950, 0.4805], grad_fn=<AddBackward0>)
tensor([ 0.8907, -1.1050, -1.5195])
tensor([ 0.8907, -1.1050, -1.5195])
tensor([2.8907, 0.8950, 0.4805])


In [32]:
weights = torch.ones(4, requires_grad=True)

for epochs in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [34]:
weights = torch.ones(4, requires_grad=True)

