In [17]:
import torch
import numpy as np

In [3]:
x  = torch.empty((4, 2, 3))
print(x)

tensor([[[ 6.0597e+13,  4.3711e-41,  6.0597e+13],
         [ 4.3711e-41, -1.5646e-16,  3.1863e-41]],

        [[-1.5646e-16,  3.1863e-41, -1.5646e-16],
         [ 3.1863e-41,  1.5905e-42,  1.1095e+27]],

        [[-1.5646e-16,  3.1863e-41,  2.5223e-44],
         [ 1.1024e+24, -1.5646e-16,  3.1863e-41]],

        [[ 1.5961e-42,  2.0621e-19, -1.5646e-16],
         [ 3.1863e-41,  2.5223e-44,  1.9823e+29]]])


In [4]:
x = torch.ones(2,3)
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [5]:
x = torch.ones(2,3, dtype=torch.int)
print(x)
print(x.dtype)
print(x.size())

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.int32
torch.Size([2, 3])


In [6]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

print("#### ADD ####")

z = x + y
w = torch.add(x, y)
print(z)
print(w)

print("#### SUB ####")

z = x - y
w = torch.sub(x, y)
print(z)
print(w)

print("#### MUL ####")

z = x * y
w = torch.mul(x, y)
print(z)
print(w)

print("#### DIV ####")

z = x / y
w = torch.div(x, y)
print(z)
print(w)

tensor([[0.5981, 0.4844],
        [0.7890, 0.6971]])
tensor([[0.8184, 0.0392],
        [0.4440, 0.3211]])
#### ADD ####
tensor([[1.4164, 0.5236],
        [1.2331, 1.0182]])
tensor([[1.4164, 0.5236],
        [1.2331, 1.0182]])
#### SUB ####
tensor([[-0.2203,  0.4453],
        [ 0.3450,  0.3760]])
tensor([[-0.2203,  0.4453],
        [ 0.3450,  0.3760]])
#### MUL ####
tensor([[0.4894, 0.0190],
        [0.3504, 0.2239]])
tensor([[0.4894, 0.0190],
        [0.3504, 0.2239]])
#### DIV ####
tensor([[ 0.7308, 12.3710],
        [ 1.7770,  2.1709]])
tensor([[ 0.7308, 12.3710],
        [ 1.7770,  2.1709]])


In [9]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1, 1].item())

tensor([[0.1935, 0.3247, 0.2479],
        [0.8752, 0.0531, 0.5607],
        [0.4754, 0.8012, 0.7099],
        [0.7831, 0.6506, 0.8263],
        [0.2351, 0.2489, 0.8941]])
tensor([0.1935, 0.8752, 0.4754, 0.7831, 0.2351])
tensor([0.8752, 0.0531, 0.5607])
0.0530625581741333


In [16]:
x = torch.rand(4, 4)
print(x)
y = x.view(-1, 8)
print(y)

tensor([[0.8145, 0.8235, 0.4593, 0.1177],
        [0.5468, 0.6079, 0.8469, 0.0146],
        [0.0324, 0.6813, 0.0558, 0.5069],
        [0.3989, 0.2631, 0.7355, 0.0402]])
tensor([[0.8145, 0.8235, 0.4593, 0.1177, 0.5468, 0.6079, 0.8469, 0.0146],
        [0.0324, 0.6813, 0.0558, 0.5069, 0.3989, 0.2631, 0.7355, 0.0402]])


In [19]:
a = torch.ones(5)
print(a)
b= a.numpy()
print(type(b))

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
a = np.ones(5)
print(a)
b= torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
